
name: Run style and unit tests for CMF

on:
  pull_request:

env: SOURCE_FOLDERS: "examples cmflib server"

jobs:
  run-tests:
    name: Test with Python ${{matrix.python_version}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.9", "3.10", "3.11"]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python_version}}

      - name: Install CMF
        run: |
          python -m pip install .[dev]

      - name: Enforce conformity to black
        run: |
          black --check $SOURCE_FOLDERS

      - name: Enforce import order
        run: |
          isort --check $SOURCE_FOLDERS